---
- name: Converge
  hosts: all
  vars:
    country: 'NL'
    email_address: 'test@test.com'
    organization_name: 'Test LTD' 
  tasks:
    - name: "Include ansible-role-httpd"
      include_role:
        name: "ansible-role-httpd"
